# BUILD
FROM altairseven/wondshared as build-env
WORKDIR /app

RUN mkdir Notifications
COPY  ./*.csproj ./Notifications/
RUN dotnet restore Notifications

COPY ./ ./Notifications
RUN dotnet publish Notifications -c Release -o out

# RUN
FROM mcr.microsoft.com/dotnet/aspnet

WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Wond.Notifications.dll"]