version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - wond

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: elasticsearch
    environment: 
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512 -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./Data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - wond

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2
    container_name: kibana
    ports: 
      - 5601:5601
    environment:
      ELASTICSERACH_URL: http://elasticsearch:9200
      ELASTICSERACH_HOSTS: http://elasticsearch:9200
    networks:
      - wond


networks:
  wond:
    driver: bridge