version: "3"
services:
  #Infraestructure Services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - public
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    container_name: elasticsearch
    environment: 
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
      #- "ES_HEAP_SIZE=1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./Data/volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - public

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2
    container_name: kibana
    ports: 
      - 5601:5601
    environment:
      ELASTICSERACH_URL: http://elasticsearch:9200
      ELASTICSERACH_HOSTS: http://elasticsearch:9200
    networks:
      - public
  #Si fuera a correr una db para cada servicio, habria que configurar multiples de estas, con diferentes subcarpetas en el volumen
  #mysqlauth:
  #  image: mysql
  #  container_name: mysqlauth
  #  restart: always
  #  environment:
  #    MYSQL_DATABASE: authdb
  #    MYSQL_USER: authdb
  #    MYSQL_PASSWORD: authdb
  #    MYSQL_ROOT_PASSWORD: root
  #  ports:
  #    - "3307:3306"
  #  volumes:
  #    - ./Data/volumes/mysql:/var/lib/mysql
  #  networks:
  #    - public

  mysqldb:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local
    ports:
      - "3307:3306"
    volumes:
      - ./Data/mysql_init:/docker-entrypoint-initdb.d
      - ./Data/volumes/mysql:/var/lib/mysql
    networks:
      - public

  #App Services:
  wondauth:
    image: altairseven/wondauth
    container_name: wondauth
    restart: unless-stopped
    ports:
      - 5800:80
    networks:
      - public
  wondnotifications:
    image: altairseven/wondnotifications
    container_name: wondnotifications
    restart: unless-stopped
    networks:
      - public
  wondparams:
    image: altairseven/wondparams
    container_name: wondparams
    restart: unless-stopped
    ports:
      - 5804:80
    networks:
      - public
  wondsells:
    image: altairseven/wondsells
    container_name: wondsells
    restart: unless-stopped
    ports:
      - 5806:80
    networks:
      - public
  wondstock:
    image: altairseven/wondstock
    container_name: wondstock
    restart: unless-stopped
    ports:
      - 5808:80
    networks:
      - public

  wondclient:
    image: altairseven/wondclientvue
    container_name: wondclient
    restart: unless-stopped
    ports:
      - 3300:80
    networks:
      - public




networks:
  public:
    driver: bridge