# BUILD
FROM altairseven/wondshared as build-env
WORKDIR /app

RUN mkdir Stock
COPY  ./*.csproj ./Stock/
RUN dotnet restore Stock

COPY ./ ./Stock
RUN dotnet publish Stock -c Release -o out

# RUN
FROM mcr.microsoft.com/dotnet/aspnet

WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Wond.Stock.dll"]