# BUILD
FROM altairseven/wondshared as build-env
WORKDIR /app

RUN mkdir Sells
COPY  ./*.csproj ./Sells/
RUN dotnet restore Sells

COPY ./ ./Sells
RUN dotnet publish Sells -c Release -o out

# RUN
FROM mcr.microsoft.com/dotnet/aspnet

WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Wond.Sells.dll"]